### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by veloxy** [pietheinstrengholt/rssmonster#10]
I can't find a license file, is it possible to add one? I'm assuming it's MIT, at least that's what the [composer file](https://github.com/pietheinstrengholt/rssmonster/blob/0889736624c6e6b5912cd0e80ab4d250af3f3d0a/composer.json#L5) says.

I wanted to add RSS Monster to the [awesome-selfhosted](https://github.com/Kickball/awesome-selfhosted) list but it requires a license.

**Comment by mtdavidson** [comment]
Composer.json ( https://github.com/pietheinstrengholt/rssmonster/blob/master/composer.json#L5 ) does say MIT but yes +1 proper license file.

**Comment by pietheinstrengholt** [comment]
I have added the license. There are indeed no restrictions, so feel free to add this to awesome-selfhosted.
