### ISSUE TITLE
Links are inactive in top menu

### ISSUE THREAD

**Issue by ekianjo** [pietheinstrengholt/rssmonster#12]
Hi, I have tried to install rssmonster on a Raspberry Pi server (Debian stretch with PHP7, Nginx) and followed all your instructions one after the other - when I finally go into the public/index.php page, I get the interface but none of the menu links ("add new feed" etc...) are active - they can be clicked but they do nothing. 

Obviously I must have something misconfigured somewhere, but do you have any idea what it could be ? 
Thanks for your help

**Comment by pietheinstrengholt** [comment]
I just tried it myself with a blank version of rssmonster. You need to use the upper right menu in the corner. A pop-up will be displayed. Use the "more info" button to add a new link. This is an area for improvement, I know, but when you use the "more info" button the pop-up will be closed and the option is provided to add a rss link. After you have added a link you can use the same pop-up dialog, but use update articles. The articles will be fetched.

**Comment by ekianjo** [comment]
I actually tried the "more info" button as well, but to no effect. Any idea what I should do to trace down the issue ?

**Comment by pietheinstrengholt** [comment]
What do you see in your debug console?

**Comment by pietheinstrengholt** [comment]
@ekianjo, I'll close this issue, because I've done a major rewrite of the entire codebase. If you're still interested in trying this out, please let me know.
