### ISSUE TITLE
No posts available at first load

### ISSUE THREAD

**Issue by trustdarkness** [pietheinstrengholt/rssmonster#13]
always shows as above and javascript console shows:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

**Comment by pietheinstrengholt** [comment]
@trustdarkness, I'll close this issue, because I've done a major rewrite of the entire codebase. If you're still interested in trying this out, please let me know.
