### ISSUE TITLE
Does RSSmonster support the "hot" links feature?

### ISSUE THREAD

**Issue by dylan-k** [pietheinstrengholt/rssmonster#15]
Since Fever has stopped development, I'm looking for another way to find "hot" links in my RSS feeds. Does RSS support this? If not, is it a planned feature?

**Comment by pietheinstrengholt** [comment]
Hi @dylan-k, it has been a while. RSSMonster features something I call starred items. These starred items will be returned when using the hot links api. Does this make any sense?

**Comment by dylan-k** [comment]
That does make sense, although it's not quite the same thing as the original feature.

**Comment by pietheinstrengholt** [comment]
I've implemented the hotlink feature. External links are extracted from all posts, and stored in a hotlink table. If the link is found in this table it is classified with the count. Here you can see how this looks in practice.

<img width="995" alt="hotlink" src="https://user-images.githubusercontent.com/186269/123974199-be04d980-d9bc-11eb-8aee-53b8f3e194c1.png">
