### ISSUE TITLE
Installation from docker now working?

### ISSUE THREAD

**Issue by cschaba** [pietheinstrengholt/rssmonster#22]
Hi I tried to install it via docker like described but when I run it I get PHP errors

Warning: require_once(/var/www/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/bootstrap/app.php on line 3

Fatal error: require_once(): Failed opening required '/var/www/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/bootstrap/app.php on line 3

What have I done wrong?

**Comment by ThinkChaos** [comment]
I have the same issue.

If I start a shell in the app container, I can see that the vendor directory is missing, even though it is created during the build.
I don't know much about docker, but I'm looking into the reason for this.

**Comment by pietheinstrengholt** [comment]
I’ll push an update. Currently the composer install runs inside the container. The makes the starting process of the container slow and causes issues like you mentioned. I’ll let you know once it’s ready.

**Comment by pietheinstrengholt** [comment]
I have updated the docker instructions and pushed some small fixes. Did a clean install on my OSX machine. Hopefully it is working now.

**Comment by pietheinstrengholt** [comment]
@ThinkChaos,

I pushed some changes to the repo for the Docker config and as of now I have everything up and working, including the database. The app automatically connects to mysql, including a health-check to avoid that the app tries to connect while the database isn't up and running.

**Comment by ThinkChaos** [comment]
This works for me with the following small changes (which aren't necessary I think):

```patch
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -19,8 +19,6 @@ services:
       DB_DATABASE: rssmonster
       DB_HOSTNAME: mysql
     working_dir: /usr/local/rssmonster/server
-    env_file:
-      - ./server/.env
     links:
       - mysql:mysql

--- a/app.dockerfile
+++ b/app.dockerfile
@@ -10,6 +10,6 @@ WORKDIR /usr/local/rssmonster/server
 RUN mv ../client/dist ./
 RUN npm install

-COPY ./server/.env.example /usr/local/rssmonster/server/.env
+#COPY ./server/.env.example /usr/local/rssmonster/server/.env
 EXPOSE 3000/tcp
 CMD npm run start
```

I did this just so that everything is in the docker files which is simpler for me because I don't run RSSMonster outside of docker.

**Comment by pietheinstrengholt** [comment]
Are you connecting to host=mysql or localhost? The database runs on a different instance, so localhost doesn’t work.

**Comment by ThinkChaos** [comment]
I'm connecting with `host=mysql`, RSSMonster actually connects correctly and I can add groups/feeds.
It's the healthcheck that triggers every 30s and causes that message.

**Comment by pietheinstrengholt** [comment]
@ThinkChaos, please let me know if everything is working. Please also see my other comment in #26.

**Comment by pietheinstrengholt** [comment]
Closing this issue since we now have a working Docker version, including a Travis CI pipeline.
