### ISSUE TITLE
Simplify configuration

### ISSUE THREAD

**Issue by ThinkChaos** [pietheinstrengholt/rssmonster#25]
I find it confusing that the sequelize conf is laying around in `server/config` but isn't used at all.
I think the best thing would be to change `server/utils/database.js` to use the sequelize config.

An advantage of using the sequelize conf would be getting 3 environments: development, test, production. You could add a `DB_ENVIRONMENT` variable to choose one of them.

`database.js` could look something like this:
```js
// I did NOT test this

require('dotenv').load();

const sequelize_config = require("../config/config.js");

const Sequelize = require('sequelize');

const cfg = sequelize_config[process.env.DB_ENVIRONMENT];
const sequelize = new Sequelize(cfg.database, cfg.username, cfg.password, cfg);

module.exports = sequelize;
```

I haven't checked in the sequelize docs if there's a method to automatically load the correct configuration from its folder, so there might be a better way to do this.

**Comment by ThinkChaos** [comment]
Another confusing point was that sequelize uses the `DB_HOSTNAME` env variable, while you use `DB_HOST`. So I spent some time wondering why RSSMonster was connecting to `localhost`.

**Comment by pietheinstrengholt** [comment]
The config.js relies on the .sequelizerc, which is needed to seed the database:

http://docs.sequelizejs.com/manual/tutorial/migrations.html

DB_HOSTNAME is a good point. I’ll investigate to harmonize this across all code.
