### ISSUE TITLE
Adding a feed fails

### ISSUE THREAD

**Issue by ThinkChaos** [pietheinstrengholt/rssmonster#31]
My guess is this only happens when there are no categories because of this: https://github.com/pietheinstrengholt/rssmonster/blob/d07b9c1b3204748e54ad6cb9561558fb1c8e0fa5/server/controllers/feed.js#L125-L126

**Comment by pietheinstrengholt** [comment]
The database seed script adds a first category. This is a temporary solution. For a final solution we might consider:

- perform a check if a category exists. If not, create one on the fly.
- assign to a default category, one the feed validation has been successful we can ask the user which category to assign the feed to.
- limit the user not removing all categories. At least one needs to be there.

**Comment by pietheinstrengholt** [comment]
Pushed some small fixes. It's not perfect yet, but should be working at least.
