### ISSUE TITLE
Feature Request: sqlite support

### ISSUE THREAD

**Issue by 9mmtylenol** [pietheinstrengholt/rssmonster#4]
I'm well aware the project is WIP but for a future reccomendation, could sqlite support be considered? I hate setting up mysql for anything, not to mention it's not a dep of anything running on my server. It would be nice to just have one file serve as the database. It's not suggested for traffic/user heavy situations but I'm only pulling feeds from small blogs.

**Comment by pietheinstrengholt** [comment]
I'm working on a rewrite using the laravel (lumen) framework. I'll push the work within a couple of days. When using laravel it is very easy to use a different database backend (e.g. sqlite).

**Comment by pietheinstrengholt** [comment]
I pushed my latest work. It is still a work in progress but many improvements already have been made. It now uses the laravel framework. The items in the sidebar are now draggable and sortable. Javascript code has been cleaned up. Etc. Some features need to be restored (add new categories, opml import and feeder api).

To use SQLite see: http://laravel-recipes.com/recipes/118/setting-up-the-sqlite-database-driver
