### ISSUE TITLE
Client npm audit critical issue

### ISSUE THREAD

**Issue by ThinkChaos** [pietheinstrengholt/rssmonster#40]
`npm audit` in client warns about a critical security issue.

**Comment by pietheinstrengholt** [comment]
I pushed a fix for this today. Can you let me if the issue has been solved? Thx!

**Comment by ThinkChaos** [comment]
Looks like it fixed: https://travis-ci.org/pietheinstrengholt/rssmonster/builds/478269529#L633 !
