### ISSUE TITLE
Separate docker for production

### ISSUE THREAD

**Issue by ThinkChaos** [pietheinstrengholt/rssmonster#45]
Because production needs aren't the same as dev ones, I want to write a separate docker-compose file optimized for that case.
This should also ease setup for new users.

**Comment by pietheinstrengholt** [comment]
I have been working on a production version today. The Dockerfile in the root of the project can be used for production. Next to that I'm also working on an instruction to have the application quickly deployed on AWS Beanstalk. Looking forward for your comments.
