### ISSUE TITLE
stuck at client installation

### ISSUE THREAD

**Issue by Karthik-MA** [pietheinstrengholt/rssmonster#59]
the program is stuck and installation and shows ```/ extract:eventsource: sill extract eventsource@1.0.7 extracted to C:\Users\Karth\rssmonster\client\node_modules\.staging\eventsource-93c5d94f (286606ms)    ```

**Comment by pietheinstrengholt** [comment]
Are you using yarn or npm to install all dependencies?

**Comment by Karthik-MA** [comment]
I am using npm to install dependencies
